### ISSUE TITLE
[FRONTEND] : Navigate to dashboard and do a location.refresh() after changing viewing currency.

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [s-i-d-d-i-s/Forge#3]
<img width="691" alt="Screenshot 2023-05-29 at 06 36 39" src="https://github.com/s-i-d-d-i-s/Forge/assets/68241942/6b96adc2-d5da-4aba-8a87-eced5d400cf3">

**Comment by s-i-d-d-i-s** [comment]
@Salty-Bear I think it's similar to the PR #2 which you made. Can you fix this as well ?

**Comment by Salty-Bear** [comment]
yep
